// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export const LOCAL_SQLITE_URL = "file:./prisma/dev.db";

function isLocalSqliteEnabled(): boolean {
  if (process.env["USE_NEON"]?.trim() === "1") return false;
  if (process.env["USE_LOCAL_DB"]?.trim() === "0") return false;
  if (process.env["USE_LOCAL_DB"]?.trim() === "1") return true;
  const url = process.env["DATABASE_URL"]?.trim();
  if (url?.startsWith("file:")) return true;
  if (
    url?.startsWith("postgresql://") ||
    url?.startsWith("postgres://")
  ) {
    return false;
  }
  if (process.env.NODE_ENV !== "production") return true;
  return false;
}

/** Prisma CLI (migrate, db push, studio) — local SQLite or Neon direct URL. */
function cliDatabaseUrl(): string {
  if (isLocalSqliteEnabled()) {
    const fileUrl = process.env["DATABASE_URL"]?.trim();
    return fileUrl?.startsWith("file:") ? fileUrl : LOCAL_SQLITE_URL;
  }

  const direct =
    process.env["DIRECT_URL"]?.trim() ||
    process.env["DATABASE_URL_UNPOOLED"]?.trim();
  if (direct) return direct;

  const pooled = process.env["DATABASE_URL"]?.trim();
  if (
    pooled?.startsWith("postgresql://") ||
    pooled?.startsWith("postgres://")
  ) {
    return pooled;
  }

  return LOCAL_SQLITE_URL;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: cliDatabaseUrl(),
  },
});
