// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
loadEnv();
loadEnv({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export const LOCAL_SQLITE_URL = "file:./prisma/dev.db";

function isLocalSqliteEnabled(): boolean {
  // Never use SQLite on Vercel (Preview/Production) — Neon must be configured.
  if (process.env["VERCEL"]?.trim() === "1") return false;
  if (process.env["USE_NEON"]?.trim() === "1") return false;
  if (process.env["USE_LOCAL_DB"]?.trim() === "0") return false;
  if (process.env["USE_LOCAL_DB"]?.trim() === "1") return true;
  const url = process.env["DATABASE_URL"]?.trim();
  if (url?.startsWith("file:")) return true;
  if (
    url?.startsWith("postgresql://") ||
    url?.startsWith("postgres://")
  ) {
    return false;
  }
  if (process.env.NODE_ENV !== "production") return true;
  return false;
}

/** Prisma CLI (migrate, db push, studio) — local SQLite or Neon direct URL. */
function cliDatabaseUrl(): string {
  if (isLocalSqliteEnabled()) {
    const fileUrl = process.env["DATABASE_URL"]?.trim();
    return fileUrl?.startsWith("file:") ? fileUrl : LOCAL_SQLITE_URL;
  }

  const direct =
    process.env["DIRECT_URL"]?.trim() ||
    process.env["DATABASE_URL_UNPOOLED"]?.trim();
  if (direct) return direct;

  const pooled = process.env["DATABASE_URL"]?.trim();
  if (
    pooled?.startsWith("postgresql://") ||
    pooled?.startsWith("postgres://")
  ) {
    return pooled;
  }

  if (process.env["VERCEL"]?.trim() === "1") {
    // `prisma generate` is the only Prisma step in the Vercel build; it reads
    // the schema and never opens a DB connection, so a real URL isn't required
    // here. Return a Postgres placeholder (never SQLite on Vercel) so builds
    // succeed even when an environment (e.g. Preview) has no DATABASE_URL.
    // Runtime queries use the real DATABASE_URL via the app's own client;
    // commands that actually connect (db push/migrate) fail loudly against this.
    console.warn(
      "[prisma.config] No Postgres DATABASE_URL in this Vercel environment — using a placeholder for `prisma generate`. Set DATABASE_URL for runtime + db push/migrate.",
    );
    return "postgresql://placeholder:placeholder@localhost:5432/placeholder";
  }

  return LOCAL_SQLITE_URL;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: cliDatabaseUrl(),
  },
});
