// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Prisma CLI (migrate, db push, studio) uses direct Neon URL — not the pooler. */
function cliDatabaseUrl(): string {
  const direct = process.env["DIRECT_URL"]?.trim();
  if (direct) return direct;

  const pooled = process.env["DATABASE_URL"]?.trim();
  if (
    pooled?.startsWith("postgresql://") ||
    pooled?.startsWith("postgres://")
  ) {
    return pooled;
  }

  // `prisma generate` does not connect; postinstall must work before .env exists
  return "postgresql://127.0.0.1:5432/placeholder?sslmode=disable";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: cliDatabaseUrl(),
  },
});
