/** Homepage Captain's Club showcase — mock until public A-6 API (M317). */

import type { CaptainClubPilot } from "@/types/captains-club";

export const HOME_FEATURED_CAPTAINS: readonly CaptainClubPilot[] = [
  {
    id: "home-captain-alex",
    initials: "AM",
    name: "Alex Morgan",
    location: "Denver, CO",
    regionGroup: "North America",
    rating: 4.9,
    ratingLabel: "4.9",
    reviewCount: 48,
    bio: "Enterprise inspection captain specializing in energy and infrastructure missions.",
    badges: ["captain", "verified", "certified"],
    tierLabel: "A-6 CAPTAIN",
    serviceIds: ["inspection"],
    specialtyLabels: ["Inspection"],
    profileHref: "/captains-club",
  },
  {
    id: "home-captain-sarah",
    initials: "SM",
    name: "Sarah Mitchell",
    location: "Austin, TX",
    regionGroup: "North America",
    rating: 5,
    ratingLabel: "5.0",
    reviewCount: 62,
    bio: "Cinematic aerial production lead for commercial and real estate clients.",
    badges: ["captain", "verified", "certified"],
    tierLabel: "A-6 CAPTAIN",
    serviceIds: ["aerial_video"],
    specialtyLabels: ["Aerial Photography"],
    profileHref: "/captains-club",
  },
  {
    id: "home-captain-james",
    initials: "JW",
    name: "James Walker",
    location: "Chicago, IL",
    regionGroup: "North America",
    rating: 4.8,
    ratingLabel: "4.8",
    reviewCount: 37,
    bio: "Mapping and surveying captain with Part 107 and advanced thermography credentials.",
    badges: ["captain", "verified", "certified"],
    tierLabel: "A-6 CAPTAIN",
    serviceIds: ["surveying"],
    specialtyLabels: ["Surveying & mapping"],
    profileHref: "/captains-club",
  },
  {
    id: "home-captain-daniel",
    initials: "DR",
    name: "Daniel Ruiz",
    location: "Miami, FL",
    regionGroup: "North America",
    rating: 4.9,
    ratingLabel: "4.9",
    reviewCount: 41,
    bio: "Public safety and event coverage captain serving enterprise and municipal clients.",
    badges: ["captain", "verified", "certified"],
    tierLabel: "A-6 CAPTAIN",
    serviceIds: ["events"],
    specialtyLabels: ["Events"],
    profileHref: "/captains-club",
  },
] as const;
