import type { PilotMissionCard } from "@/lib/pilot/marketplace-map";

/** Sample missions when marketplace API returns no open jobs (UI only). */
export const PILOT_MARKETPLACE_MOCK_JOBS: readonly PilotMissionCard[] = [
  {
    id: "mock-mission-1",
    initials: "NE",
    category: "INSPECTION",
    title: "Coastal Offshore Turbine Assessment",
    clientName: "Northwind Energy",
    rating: "4.9",
    location: "North Sea · Sector 14",
    deadline: "24 MAY · 18:00Z",
    budget: "$4,250",
    license: "FAA Part 107 + BVLOS",
    href: "/dashboard/pilot/jobs",
    hasApplied: false,
    canApply: true,
    eligibilityNote: null,
    searchText:
      "coastal offshore turbine assessment northwind energy inspection north sea sector 14 faa part 107 bvlos",
  },
  {
    id: "mock-mission-2",
    initials: "MR",
    category: "LOGISTICS",
    title: "Emergency Medical Payload Delivery",
    clientName: "MedReach Ops",
    rating: "4.8",
    location: "Appalachian Range · Zone B",
    deadline: "ASAP · HIGH PRIORITY",
    budget: "$1,800",
    license: "FAA Part 107 + Night Ops",
    href: "/dashboard/pilot/jobs",
    hasApplied: false,
    canApply: true,
    eligibilityNote: null,
    searchText:
      "emergency medical payload delivery medreach logistics appalachian faa part 107 night",
  },
  {
    id: "mock-mission-3",
    initials: "AG",
    category: "AGRICULTURE",
    title: "Precision Crop Survey",
    clientName: "AgriScope LLC",
    rating: "4.7",
    location: "California · Region IV",
    deadline: "25 MAY · 06:00Z",
    budget: "$950",
    license: "FAA Part 107",
    href: "/dashboard/pilot/jobs",
    hasApplied: false,
    canApply: true,
    eligibilityNote: null,
    searchText:
      "precision crop survey agriscope agriculture california region iv faa part 107",
  },
  {
    id: "mock-mission-4",
    initials: "EN",
    category: "ENERGY",
    title: "Sub-Station Thermal Scan",
    clientName: "GridWatch Utilities",
    rating: "4.9",
    location: "Detroit Metro · Lot 9",
    deadline: "DAILY · 09:00Z",
    budget: "$2,100",
    license: "FAA Part 107 + Thermal",
    href: "/dashboard/pilot/jobs",
    hasApplied: false,
    canApply: true,
    eligibilityNote: null,
    searchText:
      "sub-station thermal scan gridwatch energy detroit metro faa part 107 thermal",
  },
  {
    id: "mock-mission-5",
    initials: "FP",
    category: "INSPECTION",
    title: "Federal Pipeline Survey",
    clientName: "Pipeline Authority",
    rating: "4.6",
    location: "Texas Corridor · Sector 7",
    deadline: "28 MAY · 14:00Z",
    budget: "$3,600",
    license: "FAA Part 107 + BVLOS",
    href: "/dashboard/pilot/jobs",
    hasApplied: false,
    canApply: true,
    eligibilityNote: null,
    searchText:
      "federal pipeline survey pipeline authority inspection texas corridor faa part 107 bvlos",
  },
  {
    id: "mock-mission-6",
    initials: "RE",
    category: "SURVEY",
    title: "Real Estate Development Mapping",
    clientName: "Summit Developments",
    rating: "4.8",
    location: "Denver Metro · Block C",
    deadline: "30 MAY · 10:00Z",
    budget: "$1,450",
    license: "FAA Part 107",
    href: "/dashboard/pilot/jobs",
    hasApplied: false,
    canApply: true,
    eligibilityNote: null,
    searchText:
      "real estate development mapping summit developments survey denver metro faa part 107",
  },
] as const;
