export const adminNav = [
  { label: "Dashboard", href: "/dashboard/admin" },
  { label: "Users", href: "/dashboard/admin/users" },
  { label: "Pilots", href: "/dashboard/admin/pilots" },
  { label: "Clients", href: "/dashboard/admin/clients" },
  { label: "Jobs", href: "/dashboard/admin/jobs" },
  { label: "Applications", href: "/dashboard/admin/applications" },
  { label: "Bookings", href: "/dashboard/admin/bookings" },
  { label: "Reviews", href: "/dashboard/admin/reviews" },
  { label: "Payments", href: "/dashboard/admin/payments" },
  { label: "Subscriptions", href: "/dashboard/admin/subscriptions" },
  { label: "Verifications", href: "/dashboard/admin/verifications" },
  { label: "Certificates", href: "/dashboard/admin/certificates" },
  { label: "Messages", href: "/dashboard/admin/messages" },
  { label: "Support Chat", href: "/dashboard/admin/support" },
  { label: "Waitlist", href: "/dashboard/admin/waitlist" },
  { label: "Disputes", href: "/dashboard/admin/disputes" },
  { label: "Achievements / Wings", href: "/dashboard/admin/achievements" },
  { label: "Uniform Shop", href: "/dashboard/admin/shop" },
  { label: "Settings", href: "/dashboard/admin/settings" },
] as const;
